---
- name: Download Golang {{ golang_version }}
  ansible.builtin.get_url:
    url: "{{ golang_installer_url }}"
    dest: "{{ golang_installer_temp_dest }}"
    mode: "0644"

- name: Unzip Golang
  become: true
  ansible.builtin.unarchive:
    src: "{{ golang_installer_temp_dest }}"
    dest: "{{ golang_install_path }}"
    mode: "0755"
    remote_src: true

- name: Update PATH
  become: true
  ansible.builtin.copy:
    dest: /etc/profile.d/go.sh
    content: |
      export PATH=$PATH:/usr/local/go/bin
    mode: '0644'
