---
- hosts: localhost
  vars_prompt:
    - name: "user_name"
      prompt: "Enter username"
      private: false

  vars:
    user_path: /home/{{user_name}}  

  tasks:
    - include: tasks/gnome-theme.yml
