---
- hosts: localhost

  vars_prompt:
    - name: "user_name"
      prompt: "Enter username"
      private: false

  vars:
    user_path: /home/{{user_name}}  

  pre_tasks:
    - name: update apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present

    - name: install curl
      become: true
      apt:
        name: curl
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/git.yml
    - include: tasks/fonts.yml
    - include: tasks/zsh.yml
    - include: tasks/node.yml 
    - include: tasks/node-packages.yml
    - include: tasks/neovim.yml
    - include: tasks/python.yml
    - include: tasks/tmux.yml
    - include: tasks/docker.yml
    - include: tasks/dotfiles.yml
