---
- name: Install curl
  become: true
  ansible.builtin.package:
    name: curl
    state: present

- name: Download Rustup
  ansible.builtin.get_url:
    url: "{{ rustlang_installer_url }}"
    dest: "{{ rustlang_installer_temp_dest }}"
    mode: "0755"

- name: Install Rustlang
  ansible.builtin.command:
    cmd: "{{ rustlang_installer_temp_dest }} -y"
    creates: "{{ ansible_facts['user_dir'] }}/.cargo/bin/rustc"
