---
- name: Ensure clean install
  ansible.builtin.file:
    path: "{{ rustlang_installer_temp_dest }}"
    state: absent
  when: "'rust_clean_install' in ansible_run_tags"

- name: Download rustup
  ansible.builtin.get_url:
    url: "{{ rustlang_installer_url }}"
    dest: "{{ rustlang_installer_temp_dest }}"
    mode: "0755"

- name: Install rustlang with default settings
  ansible.builtin.command:
    cmd: "{{ rustlang_installer_temp_dest }} -y"
    creates: '~/.cargo/bin/rustc'
