---
# defaults file for docker
#

docker_debian_repo_url: "https://download.docker.com/linux"
docker_rhel_repo_url: "https://download.docker.com/linux/fedora/docker-ce.repo"

docker_requirements_packages:
  - ca-certificates
  - curl
  - gnupg

docker_debian_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_redhat_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_users: []

docker_release_channel: "stable"

docker_compose_version: "5.1.4"
docker_compose_url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-linux-x86_64"
