- name: Install stow
  apt:
    name: stow
  become: true

- name: Check dotfiles folder
  stat:
    path: "{{user_path}}/.dotfiles"
  register: dotfiles

- name: Delete old dotfiles
  ansible.builtin.file:
    state: absent
    path: "{{user_path}}/.dotfiles"
  become: true
  when: dotfiles.stat.exists == true

- name: Cloning dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/ReneRuprecht/.dotfiles.git'
    dest: '{{user_path}}/.dotfiles'
    update: yes
    version: main
    accept_hostkey: yes 

- name: Stow files
  shell: cd ~/.dotfiles && stow .
  become_user: '{{user_name}}'
