- name: Create fonts folder
  ansible.builtin.file:
    path: $HOME/.fonts/
    state: directory
    mode: '0755'
  tags:
    - fonts
    - zsh

- name: Install regular
  become: true
  ansible.builtin.get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf 
    dest: '{{user_path}}/.fonts/MensloNFRegular.ttf'
  tags:
    - fonts-test
    - zsh

- name: Install bold
  become: true
  ansible.builtin.get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf 
    dest: '{{user_path}}/.fonts/MensloNFBold.ttf'
  tags:
    - fonts-test
    - zsh

- name: Install italic
  become: true
  ansible.builtin.get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf 
    dest: '{{user_path}}/.fonts/MensloNFItalic.ttf'
  tags:
    - fonts-test
    - zsh

- name: Install Bold Italic
  become: true
  ansible.builtin.get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf 
    dest: '{{user_path}}/.fonts/MensloNFBoldItalic.ttf'
  tags:
    - fonts-test
    - zsh
