# neovim section        
- name: Install neovim req
  become: true
  apt:
    name:
      - cmake
      - make
      - g++
      - gcc
      - ninja-build
      - gettext
      - xsel # for clipboard
  tags:
    - neovim

- name: Remove old neovim
  ansible.builtin.file:
    state: absent
    path: "{{user_path}}/neovim" 
  become: true
  tags:
    - neovim

- name: clone neovim
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{user_path}}/neovim"
  become_user: "{{user_name}}"
  tags:
    - neovim

- name: Make neovim
  shell: cd {{user_path}}/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo
  become_user: "{{user_name}}"
  tags:
    - neovim

- name: Install neovim
  shell: cd {{user_path}}/neovim && git checkout stable &&  make install
  become: true
  tags:
    - neovim

- name: Install ripgrep
  apt:
    name:
      - ripgrep
  become: true
  tags:
    - telescope
    - neovim

- name: Install fd
  apt:
    name:
      - fd-find
  become: true
  tags:
    - telescope
    - neovim

- name: Create nvim custom debugger directory
  ansible.builtin.file:
    path: ~/.local/share/nvim/custom/debugger
    state: directory
    mode: '0755'
  tags:
    - neovim

- name: Clone php-debug
  ansible.builtin.git:
    repo: "https://github.com/xdebug/vscode-php-debug.git"
    dest: "{{user_path}}/vscode-php-debug"
  become_user: "{{user_name}}"
  tags:
    - neovim

- name: Build & install vscode-php-debug
  shell: cd {{user_path}}/vscode-php-debug && npm install && npm run build
  tags:
    - neovim

- name: Move vscode-php-debug into nvim custom debugger folder
  shell: mv {{user_path}}/vscode-php-debug {{user_path}}/.local/share/nvim/custom/debugger/ 
  tags:
    - neovim
