- name: Update node package deb to v18
  shell:  curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
  tags:
    - node

- name: Install node and npm
  become: true
  apt:
    name:
      - nodejs
  tags:
    - node
