# tmux section
- name: Install tmux
  become: true
  apt:
    name: tmux 
  tags:
    - tmux

- name: Check tmux.conf
  stat:
    path: $HOME/.tmux.conf
  register: tmux_conf
  tags:
    - tmux
    
- name: Delete old plugin manager
  ansible.builtin.file:
    state: absent
    path: "{{user_path}}/.tmux.conf"
  when: tmux_conf.stat.exists == true
  tags:
    - tmux

- name: Check tmux plugin installed
  stat:
    path: $HOME/.tmux/plugins/tpm
  register: tmux_plugin_manager
  tags:
    - tmux

- name: Delete old plugin manager
  ansible.builtin.file:
    state: absent
    path: "{{user_path}}/.tmux/plugins/tpm"
  become: true
  when: tmux_plugin_manager.stat.exists == true
  tags:
    - tmux

- name: Install tmux plugin manager
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "~/.tmux/plugins/tpm"
  become_user: "{{user_name}}"
  tags:
    - tmux
