# tmux section
- name: Install tmux
  become: true
  apt:
    name: tmux 
  tags:
    - tmux
    
- name: Delete old plugin manager
  ansible.builtin.file:
    state: absent
    path: "{{user_path}}/.tmux.conf"
  tags:
    - tmux

- name: Delete old plugin manager
  ansible.builtin.file:
    state: absent
    path: "{{user_path}}/.tmux/plugins/tpm"
  become: true
  tags:
    - tmux

- name: Install tmux plugin manager
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "~/.tmux/plugins/tpm"
  become_user: "{{user_name}}"
  tags:
    - tmux
