# zsh section
- name: Install zsh
  become: true
  apt:
    name: zsh
  tags:
    - zsh

- name: Set zsh shell
  user:
    name: "{{user_name}}"
    shell: "/bin/zsh"
    state: present
  become: yes
  tags:
    - zsh

- name: Remove old zshrc
  ansible.builtin.file:
    state: absent
    path: "{{user_path}}/.zshrc" 
  become: true
  tags:
    - zsh

- name: Download oh-my-zsh installer
  become: true
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: '{{user_path}}/.oh-my-installer'
    mode: a+x
  tags:
    - zsh

- name: Remove old oh-my-zsh
  ansible.builtin.file:
    state: absent
    path: "{{user_path}}/.oh-my-zsh" 
  become: true
  tags:
    - zsh

- name: Install oh-my-zsh
  shell: $HOME/.oh-my-installer
  become_user: "{{user_name}}"
  tags:
    - zsh

- name: Remove old p10k
  ansible.builtin.file:
    state: absent
    path: $HOME/.p10k.zsh
  become: true
  tags:
    - zsh

- name: Remove old powerlevel10k
  ansible.builtin.file:
    state: absent
    path: $HOME/.oh-my-zsh/custom/themes/powerlevel10k
  become: true
  tags:
    - zsh


- name: Install powerlevel10k
  shell: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
  tags:
    - zsh

- name: Remove old zshrc
  ansible.builtin.file:
    state: absent
    path: "{{user_path}}/.zshrc" 
  become: true
  tags:
    - zsh
