- name: Install Required Packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ dotfiles_required_packages }}"

- name: Cloning dotfiles
  ansible.builtin.git:
    repo: "{{ dotfiles_repo_url }}"
    dest: "{{ ansible_facts['user_dir'] }}/.dotfiles"
    update: true
    version: main
    accept_hostkey: true

- name: Stow dotfiles
  ansible.builtin.command:
    cmd: "stow ."
    chdir: "{{ ansible_facts['user_dir'] }}/.dotfiles"
  changed_when: false
