---
- name: "[Debian] Include Prepare"
  ansible.builtin.include_tasks: "prepare_debian.yml"
  when: "ansible_facts['os_family'] | lower == 'debian'"

- name: "[RedHat] Include Prepare"
  ansible.builtin.include_tasks: "prepare_redhat.yml"
  when: "ansible_facts['os_family'] | lower == 'redhat'"

- name: Install code
  become: true
  ansible.builtin.package:
    name: code
    state: present

- name: Include Install Extensions
  ansible.builtin.include_tasks: "install_extensions.yml"
