---
- name: "[RedHat] Import gpg Key"
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: "[RedHat] Add VSCode Repo"
  become: true
  ansible.builtin.yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    repo_gpgcheck: false
