---
zsh_packages:
  - "zsh"

zsh_oh_my_zsh_installer_url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
zsh_powerlevel10k_git: "https://github.com/romkatv/powerlevel10k.git"
