---
# tasks file for general
- name: Include OS Vars
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Include Install
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}_install.yml"
