---
- name: Check old old oh-my-zsh
  ansible.builtin.stat:
    path: "$HOME/.oh-my-zsh"
  register: zsh

- name: Set zsh shell
  become: true
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    shell: "/bin/zsh"
    state: present
  when: >
    "'zsh_force_reinstall' in ansible_run_tags" or
    not zsh.stat.exists

- name: Remove old zshrc
  ansible.builtin.file:
    state: absent
    path: "$HOME/.zshrc"
  when: >
    "'zsh_force_reinstall' in ansible_run_tags" or
    not zsh.stat.exists
