---
- name: Ensure Fonts Folder Exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.fonts/"
    state: directory
    mode: "0755"

- name: Install Fonts
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ ansible_facts['user_dir'] }}/.fonts/{{ item.filename }}"
    mode: "0644"
  loop: "{{ zsh_fonts }}"
