---
- name: Create fonts folder
  ansible.builtin.file:
    path: ~/.fonts/
    state: directory
    mode: "0755"

- name: Install Fonts
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "~/.fonts/{{ item.filename }}"
    mode: "0644"
  loop: "{{ zsh_fonts }}"
