---
- name: Ensure Theme Directory Exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.oh-my-zsh/custom/themes/powerlevel10k"
    state: directory
    mode: "0755"

- name: Install powerlevel10k {{ zsh_powerlevel10k_git_version }}
  ansible.builtin.git:
    repo: "{{ zsh_powerlevel10k_git }}"
    dest: "{{ ansible_facts['user_dir'] }}/.oh-my-zsh/custom/themes/powerlevel10k"
    version: "{{ zsh_powerlevel10k_git_version }}"
