---
- name: Check libvirtd Installed
  ansible.builtin.command:
    cmd: "libvirtd --version"
  register: virtual_libvirtd_installed_version
  no_log: true
  ignore_errors: true
  changed_when: false

- name: Check kvm Installed
  ansible.builtin.command:
    cmd: "kvm --version"
  register: virtual_kvm_installed_version
  no_log: true
  ignore_errors: true
  changed_when: false
