---
- name: Adding User To Group Kvm
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    groups: kvm
    append: true
  loop: "{{ virtual_users }}"

- name: Adding User To Group Libvirt
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    groups: libvirt
    append: true
  loop: "{{ virtual_users }}"
