---
- name: Include install
  ansible.builtin.include_tasks: "install.yml"

- name: Include Configuration
  ansible.builtin.include_tasks: "configure.yml"

- name: Start and Enable libvirtd
  become: true
  ansible.builtin.service:
    name: libvirtd
    state: started
    enabled: true
