---
- name: Include OS Vars
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"


- name: Include Check
  ansible.builtin.include_tasks: "check.yml"

- name: Include debian install
  ansible.builtin.include_tasks: "debian.yml "
  when:
    - ansible_os_family | lower == 'debian'
    - virtual_kvm_installed_version.rc != 0
    - virtual_libvirtd_installed_version.rc != 0

- name: Include Configuration
  ansible.builtin.include_tasks: "configure.yml"
  when:
    - virtual_kvm_installed_version.rc != 0
    - virtual_libvirtd_installed_version.rc != 0
