---
- name: Setup Git Config
  community.general.git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop:
    - { name: 'user.name', value: "{{ git_config.name }}" }
    - { name: 'user.email', value: "{{ git_config.email }}" }
    - { name: 'core.editor', value: "{{ git_config.editor }}" }
