---
- name: Install Tmux
  become: true
  ansible.builtin.package:
    name: tmux
  loop: "{{ tmux_packages }}"

- name: Delete Old Plugin Manager
  ansible.builtin.file:
    state: absent
    path: "$HOME/.tmux.conf"

- name: Delete Old Plugin Manager
  ansible.builtin.file:
    state: absent
    path: "$HOME/.tmux/plugins/tpm"

- name: Install Tmux Plugin Manager
  ansible.builtin.git:
    repo: "{{ tmux_repo }}"
    dest: "{{ tmux_plugin_manager_dest }}"
