---
- name: Install curl
  become: true
  ansible.builtin.package:
    name: curl
    state: present

- name: Download nvm {{ node_nvm_version }}
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/{{ node_nvm_version }}/install.sh
    dest: "{{ node_nvm_download_dest }}"
    mode: "0755"

- name: Install nvm {{ node_nvm_version }}
  ansible.builtin.command:
    cmd: "{{ node_nvm_download_dest }}"
    creates: "{{ ansible_facts['user_dir'] }}/.nvm/nvm.sh"

- name: Install node {{ node_version }}
  ansible.builtin.shell:
    cmd: |
      source ~/.nvm/nvm.sh
      nvm install {{ node_version }}
      nvm alias default {{ node_version }}
    executable: /bin/bash
  register: "node_install_output"
  changed_when: "'is already installed' not in node_install_output.stderr"
  failed_when: "'Now using node' not in node_install_output.stdout"
