---
# tasks file for docker
- name: Include Install Requirements
  ansible.builtin.include_tasks: "install_requirements.yml"

- name: "[Debian] Include Install"
  ansible.builtin.include_tasks: "install_docker_debian.yml"
  when: "ansible_facts['os_family'] == 'Debian'"

- name: "[RedHat] Include Install"
  ansible.builtin.include_tasks: "install_docker_redhat.yml"
  when: "ansible_facts['os_family'] == 'RedHat'"

- name: Adding User To Group docker
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"

- name: Include Compose
  ansible.builtin.include_tasks: "install_docker_compose.yml"
