---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
  default_box: 'debian/bookworm64'

platforms:
  - name: debian12_rustlang
    hostname: debian12rustlang
    instance_raw_config_args:
      - 'vm.synced_folder ".", "/vagrant", type: "rsync"'
      - 'vm.provision :shell, inline: "uname"'
    config_options:
      ssh.keep_alive: true
      ssh.remote_user: 'vagrant'
      synced_folder: true
    box: debian/bookworm64
    memory: 512
    cpus: 1
