---
- name: Remove old neovim
  ansible.builtin.file:
    state: absent
    path: "$HOME/neovim"

- name: Clone Neovim
  ansible.builtin.git:
    repo: "{{ neovim_repo }}"
    dest: "$HOME/neovim"
    force: true

- name: Checkout Neovim
  ansible.builtin.command:
    cmd: "git checkout stable"
  args:
    chdir: "$HOME/neovim"

- name: Make Neovim
  ansible.builtin.command:
    cmd: "make CMAKE_BUILD_TYPE=RelWithDebInfo"
    chdir: "$HOME/neovim"

- name: Install neovim
  ansible.builtin.command:
    cmd: "make install"
  args:
    chdir: "$HOME/neovim"

- name: Install Python Neovim
  become: true
  ansible.builtin.package:
    name: python3-neovim
