---
- name: Download Neovim {{ neovim_version }}
  ansible.builtin.get_url:
    url: "{{ neovim_url }}"
    dest: "{{ neovim_temp_dest }}"
    mode: "0644"

- name: Ensure Directory Exists
  become: true
  ansible.builtin.file:
    path: "{{ neovim_install_path }}"
    state: directory
    mode: "0755"

- name: Unzip Neovim
  become: true
  ansible.builtin.unarchive:
    src: "{{ neovim_temp_dest }}"
    dest: "{{ neovim_install_path }}"
    mode: "0755"
    remote_src: true
    extra_opts:
      - "--strip-components=1"
    creates: "{{ neovim_install_path }}/bin"

- name: Update PATH
  become: true
  ansible.builtin.copy:
    dest: /etc/profile.d/go.sh
    content: |
      export PATH=$PATH:{{ neovim_install_path_bin }}
    mode: '0644'
